# Generated by Django 3.2.3 on 2022-02-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220204_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='facial',
        ),
        migrations.DeleteModel(
            name='massage',
        ),
        migrations.RemoveField(
            model_name='images',
            name='service',
        ),
    ]
