# Generated by Django 3.2.3 on 2022-02-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220204_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='services',
            field=models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3')], default=1, max_length=120, verbose_name='Select Service'),
            preserve_default=False,
        ),
    ]
