# Generated by Django 3.2.3 on 2023-01-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220304_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='services',
            field=models.CharField(choices=[('skincare', 'skincare'), ('massage', 'massage'), ('facial', 'facial'), ('piercing', 'piercing'), ('hair_treatment', 'hair_treatment'), ('nail_treatment', 'nail_treatment')], max_length=120, verbose_name='Select Service'),
        ),
    ]
