# Generated by Django 3.2.3 on 2023-01-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_images_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='services',
            field=models.CharField(choices=[('skincare', 'skincare'), ('massage', 'massage'), ('facial', 'facial'), ('piercing', 'piercing'), ('hair treatment', 'hair treatment'), ('nail treatment', 'nail treatment')], max_length=120, verbose_name='Select Service'),
        ),
    ]
