# Generated by Django 3.2.3 on 2023-02-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_images_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='subject',
            field=models.CharField(default=60, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
