# Generated by Django 3.2.3 on 2023-03-02 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_visitor_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='', verbose_name='Surname')),
                ('name', models.CharField(max_length=100, verbose_name='First name')),
                ('gmail', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=100)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='visitors',
        ),
    ]
